### ISSUE TITLE
How to include a service without nuxt intercepting

### ISSUE THREAD

**Issue by irthos** [silvestreh/feathers-nuxt#1]
Hi, I see there's little activity in this repo although it's a valiant goal. Aside from updating deps to latest versions, everything works as expected. However, When I use feathers to install a service (neDB), I cannot post to localhost:3030/messages without getting a 404 returned as html. Is there a proper way to do this?

**Comment by silvestreh** [comment]
Hey @irthos … this repo is basically unmaintained while Nuxt is still in alpha. Once Nuxt's reaches beta and its API freezes I'll resume working on this.

With that said, you can use this snippet:

```javascript
// your-app/src/middleware/index.js

const handler = require('feathers-errors/handler');
const notFound = require('feathers-errors/not-found');
const nuxt = require('./nuxt'); // <- Require the middleware

module.exports = function () {
    // Add your custom middleware here. Remember, that
    // in Express the order matters, `notFound` and
    // the error handler have to go last.
    const app = this;

    // Use Nuxt's render middleware
    app.use((req, res, next) => {
      switch (req.accepts('html', 'json')) {
          case 'json':
            next();
            break;
          default:
            nuxt.render(req, res, next);
      }
    });

    app.use(notFound());
    app.use(handler());
};
```

**Comment by silvestreh** [comment]
I updated the code to work with Nuxt 1.0.0-RC11 … Remember that if you want to hit the API you'll need to pass an `Accept=application/json` header in your request.

<img width="1210" alt="captura de pantalla 2017-09-12 a la s 15 53 17" src="https://user-images.githubusercontent.com/1133339/30343086-8603b43c-97d2-11e7-8159-a040518c6d30.png">
