### ISSUE TITLE
Nuxt store using deprecated Classic mode

### ISSUE THREAD

**Issue by headghost** [silvestreh/feathers-nuxt#15]
Nuxt Vuex store's Classic mode being deprecated, the demo should implement Modules mode.

**Comment by silvestreh** [comment]
Yup, I'm aware of it. Still not sure if `feathers-vuex` supports the modules pattern. Still looking into it 😉

**Comment by silvestreh** [comment]
I'm reopening because it's still an issue

**Comment by headghost** [comment]
No problem! Thanks, I'll be watching

**Comment by TimNZ** [comment]
@silvestreh so confirmed that nuxt vuex modules mode not supported?

I'm surprised no-one has created an issue for it in feathers-vuex since classic is deprecated.

(Complete noob here researching tech stack before I commit)

**Comment by TimNZ** [comment]
I just replicated the example Nuxt has for vuex modules in this repo

client/store/index.js
```
import feathersClient from '../feathers-client';
import feathersVuex, { initAuth } from 'feathers-vuex';

const { service, auth } = feathersVuex(feathersClient, { idField: '_id' });

export const state = () => ({})

export const actions = {
  nuxtServerInit({ commit, dispatch }, { req }) {
    return initAuth({
      commit,
      dispatch,
      req,
      moduleName: 'auth',
      cookieName: 'feathers-jwt'
    })
  }
}

export const plugins = [
  service('users'),
  auth({
    state: { publicPages: ['index', 'authenticate'] },
    userService: 'users'
  })

]
```

created 'client/store/todos.js'
```
export const state = () => ({
  version: 10
})
```

and tweaked index.vue
```
<h2>{{ $store.state.todos.version }}</h2>
```

Output as expected:
```
Feathers + Nuxt
10
This is a very basic demo/boilerplate for nuxt + feathers + feathers-vuex.
```

Am I doing something right or wrong or misunderstanding?

**Comment by silvestreh** [comment]
K, just updated this. It was easier than it seemed. @TimNZ, the way you described it's the way it should work.
