### ISSUE TITLE
Server-rendered auth

### ISSUE THREAD

**Issue by jarnojellesma** [silvestreh/feathers-nuxt#2]
Hi Silvestre,

I've seen your Feathers-Nuxt project, and I was wondering if you have any plans to fix the server-rendered authentication?

I'm really struggling to make this work, and if you have any advice it would be really appreciated.

Kind regards,

Jarno

**Comment by silvestreh** [comment]
hey @jarnojellesma yeah, I plan to fix everything! I believe Nuxt is pretty close to reach a stable 1.0 release, so I'll probably start digging once again into this 😄

**Comment by jarnojellesma** [comment]
Awesome man @silvestreh 

Will keep a check on this ;)

**Comment by bin4ryio** [comment]
I changed check-auth.js a bit and everything is working for me.
```
function getTokenFromRequest (req) {
  if (!req || !req.headers || !req.headers.cookie) return
  const jwtCookie = req.headers.cookie.split(';').find(c => c.trim().startsWith(`${cookieName}=`))
  if (!jwtCookie) return
  return jwtCookie.split('=')[1]
}
```

**Comment by silvestreh** [comment]
Alright… I just updated the code to work with Nuxt 1.0.0-RC11

**Comment by revan2006** [comment]
I just updated new code for you, when i **npm run dev** is still error **NotAuthenticated: invalid signature**
