### ISSUE TITLE
Hello, how change postgresql to rethinkdb ? 

### ISSUE THREAD

**Issue by andysay** [silvestreh/feathers-nuxt#4]
Hello, how change postgresql to rethinkdb ?  thanks

**Comment by silvestreh** [comment]
You could generate another Feathers app and incorporate the little extra bits of code in this repo. There's really not much going on.

**Comment by andysay** [comment]
okay thank you!

**Comment by silvestreh** [comment]
You can check the Medium article about it https://blog.feathersjs.com/ssr-vuejs-app-with-feathers-and-nuxt-bb7dfd3e6397 … Please do note that it's outdated

**Comment by andysay** [comment]
thanks @silvestreh
