### ISSUE TITLE
How test api services ?

### ISSUE THREAD

**Issue by andysay** [silvestreh/feathers-nuxt#6]
Hello, how test api services ? .. i'm try get data from service, but work nuxt route..

**Comment by silvestreh** [comment]
you should use content headers to hit the API and get json back.

**Comment by andysay** [comment]
its work, but i found bug, if you auth, and refresh web page cntl+f5, all users get your accessToken , and can go to protected section.. lets try dot it. and fix)) thank you!

**Comment by shanekenyon87** [comment]
Can you elaborate on this?  I have been trying to directly call the APIs from my Ava tests using Axios but am only getting 404 errors.

```javascript
test.before('Init Nuxt.js', async t => {
  // stuff...
  nuxt.listen(4000, 'localhost')
  // Set base URL for axios to the nuxt server
  axios.defaults.baseURL = 'http://localhost:4000'
})
test('Route /api exists and emits json', async t => {
  try {
    const response = await axios.get('/api')
    logger.info(`response.data = ` + response.data)
    // expected response.data: json string
```

**Comment by silvestreh** [comment]
By reading Axios docs, I figure you'd need something like this.

```javascript
test.before('Init Nuxt.js', async t => {
  // stuff...
  nuxt.listen(4000, 'localhost')
  // Set base URL for axios to the nuxt server
  axios.defaults.baseURL = 'http://localhost:4000'
  axios.defaults.headers.common['Accept'] = 'application/json'
})
test('Route /api exists and emits json', async t => {
  try {
    const response = await axios.get('/api')
    logger.info(`response.data = ` + response.data)
    // expected response.data: json string
```

If that header isn't set to `'application/json'` then Nuxt will try to render something that's not there.

**Comment by shanekenyon87** [comment]
Well that isn't going to solve for a 404 as NUXT isn't serving anything *at all*.

**Comment by silvestreh** [comment]
Then this repo is probably broken. I haven't updated it for a while and I was using an alpha release of Nuxt. I have to update it, but it's hard to find the time to do it.

**Comment by shanekenyon87** [comment]
I have some working code I’ll share!

**Comment by cameronblandford** [comment]
@shanekenyon87 do you still have that working code by chance? 😮

**Comment by silvestreh** [comment]
This repo has been updated to use Feathers 3 and Nuxt 2.4. In addition, the Nuxt middleware won't have effect when running tests for your API.
