### ISSUE TITLE
package.json dev script not cross-env

### ISSUE THREAD

**Issue by jklarenbeek** [silvestreh/feathers-nuxt#9]
Hi,

fixed this issue by adding the cross-env dependency
npm i --save-dev cross-env 

and added cross-env as first command for dev and start scripts.
  "dev": "cross-env DEBUG=nuxt:* nodemon --watch src/ --watch config/ src/index.js",
  "start": "cross-env NODE_ENV=production node src/",

**Comment by silvestreh** [comment]
Done!
